### ISSUE TITLE
help

### ISSUE THREAD

**Issue by markrharvey** [kevinmcaleer/keypad#1]
is there a way to only get the key pressed once as i would like to use this for a door lock and could you store the keys pressed in a variable to check against the passcode to get in

would you be able to help

**Comment by kevinmcaleer** [comment]
Sure - you just need to an extra variable to store if a key has been pressed already or not:

```python
old_key = ""
already_pressed = False

key = keypad.get_key()
if key == old_key:
  print('you already pressed this')
else:
  old_key = key



```

**Comment by markrharvey** [comment]
Just a quick question where should I put this and how could I check
against it so say I put a variable code with the code 1111 how do I use the
keys pressed to put into a variable called enteredcode and check that
against code

Thanks for the help
